/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/targets': typeof AuthenticatedTargetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/targets': typeof AuthenticatedTargetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/leads'
    | '/outreach'
    | '/signals'
    | '/targets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/leads'
    | '/outreach'
    | '/signals'
    | '/targets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/leads'
    | '/_authenticated/outreach'
    | '/_authenticated/signals'
    | '/_authenticated/targets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
