/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubspotCallbackRouteImport } from './routes/hubspot/callback'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSignalsRouteImport } from './routes/_authenticated/signals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedHiringRouteImport } from './routes/_authenticated/hiring'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedTalentRouteRouteImport } from './routes/_authenticated/talent/route'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubspotCallbackRoute = HubspotCallbackRouteImport.update({
  id: '/hubspot/callback',
  path: '/hubspot/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSignalsRoute = AuthenticatedSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHiringRoute = AuthenticatedHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalentRouteRoute =
  AuthenticatedTalentRouteRouteImport.update({
    id: '/talent',
    path: '/talent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof AuthenticatedTalentRouteRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app': typeof AuthenticatedAppRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/hiring': typeof AuthenticatedHiringRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/hubspot/callback': typeof HubspotCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talent': typeof AuthenticatedTalentRouteRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app': typeof AuthenticatedAppRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/hiring': typeof AuthenticatedHiringRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/signals': typeof AuthenticatedSignalsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/hubspot/callback': typeof HubspotCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/talent': typeof AuthenticatedTalentRouteRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/hiring': typeof AuthenticatedHiringRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/signals': typeof AuthenticatedSignalsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/hubspot/callback': typeof HubspotCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/talent'
    | '/analytics'
    | '/app'
    | '/automation'
    | '/crm'
    | '/hiring'
    | '/leads'
    | '/outreach'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/signals'
    | '/targets'
    | '/hubspot/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/talent'
    | '/analytics'
    | '/app'
    | '/automation'
    | '/crm'
    | '/hiring'
    | '/leads'
    | '/outreach'
    | '/pipeline'
    | '/reports'
    | '/settings'
    | '/signals'
    | '/targets'
    | '/hubspot/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/talent'
    | '/_authenticated/analytics'
    | '/_authenticated/app'
    | '/_authenticated/automation'
    | '/_authenticated/crm'
    | '/_authenticated/hiring'
    | '/_authenticated/leads'
    | '/_authenticated/outreach'
    | '/_authenticated/pipeline'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/signals'
    | '/_authenticated/targets'
    | '/hubspot/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  HubspotCallbackRoute: typeof HubspotCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubspot/callback': {
      id: '/hubspot/callback'
      path: '/hubspot/callback'
      fullPath: '/hubspot/callback'
      preLoaderRoute: typeof HubspotCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/signals': {
      id: '/_authenticated/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AuthenticatedSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hiring': {
      id: '/_authenticated/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof AuthenticatedHiringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talent': {
      id: '/_authenticated/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof AuthenticatedTalentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTalentRouteRoute: typeof AuthenticatedTalentRouteRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedHiringRoute: typeof AuthenticatedHiringRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSignalsRoute: typeof AuthenticatedSignalsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTalentRouteRoute: AuthenticatedTalentRouteRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedHiringRoute: AuthenticatedHiringRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSignalsRoute: AuthenticatedSignalsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  HubspotCallbackRoute: HubspotCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
