import type { TalentCandidate } from "./talent.types";

export const SEED_CANDIDATES: Omit<
  TalentCandidate,
  "id" | "user_id" | "created_at" | "updated_at"
>[] = [
  {
    name: "Priya Sharma",
    title: "Senior React Developer",
    email: "priya.s@example.com",
    location: "San Francisco, CA",
    remote_preference: "Hybrid",
    years_experience: 7,
    expected_salary: "$165,000",
    industry: "FinTech",
    availability: "2 weeks",
    education: "MS Computer Science, Stanford",
    skills: {
      programming_languages: ["TypeScript", "JavaScript", "Python"],
      frameworks: ["React", "Next.js", "Node.js", "TanStack Query"],
      ai_ml: ["TensorFlow.js", "OpenAI API"],
      llm_experience: ["RAG pipelines", "Prompt engineering"],
      cloud: ["AWS", "Vercel"],
      devops: ["Docker", "GitHub Actions", "CI/CD"],
      databases: ["PostgreSQL", "Redis", "Supabase"],
      certifications: ["AWS Solutions Architect"],
      soft_skills: ["Team leadership", "Mentoring", "Cross-functional collaboration"],
      open_source: ["react-component-library (2.1k stars)", "tanstack-hooks-utils"],
      projects: ["Real-time trading dashboard", "Design system for enterprise SaaS"],
    },
    analysis: {
      ai_match_score: 94,
      skill_match: 92,
      resume_summary:
        "Senior frontend engineer with deep React expertise and growing AI integration experience. Strong track record building performant enterprise UIs.",
      strengths: [
        "Expert React/TypeScript",
        "Design systems",
        "AI-augmented features",
        "Open source presence",
      ],
      weaknesses: ["Limited backend depth", "No formal ML research background"],
      recommended_role: "Senior React Developer / Frontend Tech Lead",
      leadership_score: 82,
      technical_score: 91,
      communication_score: 88,
      learning_potential: 90,
      career_growth_prediction:
        "Likely to grow into Staff Engineer or Frontend Architect within 2-3 years.",
      rank: "excellent",
    },
    pipeline_stage: "interview",
    sources: [
      { type: "github", url: "https://github.com/priyasharma", label: "GitHub Profile" },
      { type: "portfolio", url: "https://priyadev.io", label: "Portfolio" },
      { type: "resume", label: "Uploaded Resume" },
    ],
    github_url: "https://github.com/priyasharma",
    portfolio_url: "https://priyadev.io",
  },
  {
    name: "Marcus Chen",
    title: "LLM Engineer",
    email: "marcus.chen@example.com",
    location: "Seattle, WA",
    remote_preference: "Remote",
    years_experience: 5,
    expected_salary: "$185,000",
    industry: "AI/ML",
    availability: "Immediate",
    education: "PhD Machine Learning, MIT",
    skills: {
      programming_languages: ["Python", "Rust", "C++"],
      frameworks: ["PyTorch", "LangChain", "vLLM", "FastAPI"],
      ai_ml: ["Transformers", "Fine-tuning", "RLHF", "Evaluation harnesses"],
      llm_experience: ["GPT-4 fine-tuning", "RAG", "Agent orchestration", "Prompt optimization"],
      cloud: ["GCP", "AWS SageMaker"],
      devops: ["Kubernetes", "MLflow", "Weights & Biases"],
      databases: ["Pinecone", "Weaviate", "PostgreSQL"],
      certifications: ["Google Cloud ML Engineer"],
      soft_skills: ["Research communication", "Technical writing"],
      open_source: ["llm-eval-kit (890 stars)", "rag-pipeline-starter"],
      projects: ["Enterprise RAG platform", "Multi-agent coding assistant"],
    },
    analysis: {
      ai_match_score: 97,
      skill_match: 96,
      resume_summary:
        "PhD-level ML engineer specializing in LLM systems, RAG, and production AI pipelines. Published researcher with strong open-source contributions.",
      strengths: [
        "Deep LLM expertise",
        "Production ML systems",
        "Research background",
        "Agent architecture",
      ],
      weaknesses: ["Less frontend experience", "Prefers research-heavy roles"],
      recommended_role: "Staff LLM Engineer / AI Platform Lead",
      leadership_score: 75,
      technical_score: 98,
      communication_score: 85,
      learning_potential: 95,
      career_growth_prediction: "High potential for AI Research Lead or Principal Engineer role.",
      rank: "excellent",
    },
    pipeline_stage: "offer",
    sources: [
      { type: "github", url: "https://github.com/marcuschen", label: "GitHub" },
      { type: "kaggle", url: "https://kaggle.com/marcuschen", label: "Kaggle" },
      { type: "publication", label: "3 NeurIPS/ICML papers" },
    ],
    github_url: "https://github.com/marcuschen",
  },
  {
    name: "Elena Rodriguez",
    title: "AI Researcher",
    email: "elena.r@example.com",
    location: "Boston, MA",
    remote_preference: "On-site",
    years_experience: 8,
    expected_salary: "$195,000",
    industry: "Healthcare AI",
    availability: "1 month",
    education: "PhD Computer Science, Carnegie Mellon",
    skills: {
      programming_languages: ["Python", "Julia", "R"],
      frameworks: ["PyTorch", "JAX", "Hugging Face"],
      ai_ml: ["Computer vision", "NLP", "Multimodal models", "Clinical NLP"],
      llm_experience: ["Medical LLM fine-tuning", "HIPAA-compliant RAG"],
      cloud: ["Azure", "AWS"],
      devops: ["Docker", "Airflow"],
      databases: ["MongoDB", "PostgreSQL", "FHIR data stores"],
      certifications: ["HIPAA compliance training"],
      soft_skills: ["Cross-disciplinary collaboration", "Grant writing"],
      open_source: ["med-nlp-benchmark (450 stars)"],
      projects: ["Clinical decision support AI", "Radiology report summarization"],
    },
    analysis: {
      ai_match_score: 91,
      skill_match: 89,
      resume_summary:
        "Research-focused AI scientist with healthcare domain expertise and published work in clinical NLP and multimodal AI.",
      strengths: ["Research pedigree", "Domain expertise", "Multimodal AI", "Regulatory awareness"],
      weaknesses: ["Slower to ship product features", "Higher salary expectations"],
      recommended_role: "Senior AI Researcher / Applied Scientist",
      leadership_score: 78,
      technical_score: 94,
      communication_score: 90,
      learning_potential: 88,
      career_growth_prediction:
        "Path to Principal Scientist or Research Director in healthcare AI.",
      rank: "excellent",
    },
    pipeline_stage: "screening",
    sources: [
      { type: "publication", label: "12 peer-reviewed papers" },
      { type: "portfolio", url: "https://elenarodriguez.ai", label: "Research Portfolio" },
    ],
    portfolio_url: "https://elenarodriguez.ai",
  },
  {
    name: "James Okonkwo",
    title: "Python Backend Engineer",
    email: "james.o@example.com",
    location: "Austin, TX",
    remote_preference: "Remote",
    years_experience: 6,
    expected_salary: "$145,000",
    industry: "E-commerce",
    availability: "3 weeks",
    education: "BS Computer Engineering, UT Austin",
    skills: {
      programming_languages: ["Python", "Go", "SQL"],
      frameworks: ["Django", "FastAPI", "Celery", "gRPC"],
      ai_ml: ["scikit-learn", "Basic NLP"],
      llm_experience: ["OpenAI API integration"],
      cloud: ["AWS", "DigitalOcean"],
      devops: ["Terraform", "Docker", "GitLab CI"],
      databases: ["PostgreSQL", "Redis", "Elasticsearch"],
      certifications: ["AWS Developer Associate"],
      soft_skills: ["Problem solving", "Code review culture"],
      open_source: ["fastapi-auth-utils (320 stars)"],
      projects: ["High-throughput order processing", "Microservices migration"],
    },
    analysis: {
      ai_match_score: 86,
      skill_match: 88,
      resume_summary:
        "Solid backend engineer with strong Python skills and experience scaling e-commerce systems. Growing AI integration capabilities.",
      strengths: [
        "Scalable backend architecture",
        "API design",
        "Database optimization",
        "DevOps fluency",
      ],
      weaknesses: ["Limited AI/ML depth", "No team lead experience"],
      recommended_role: "Senior Python Backend Engineer",
      leadership_score: 65,
      technical_score: 89,
      communication_score: 80,
      learning_potential: 85,
      career_growth_prediction: "Strong IC track; could lead backend team with mentorship.",
      rank: "strong",
    },
    pipeline_stage: "sourced",
    sources: [
      { type: "github", url: "https://github.com/jamesokonkwo", label: "GitHub" },
      {
        type: "stackoverflow",
        url: "https://stackoverflow.com/users/jameso",
        label: "Stack Overflow",
      },
    ],
    github_url: "https://github.com/jamesokonkwo",
  },
  {
    name: "Sofia Nakamura",
    title: "Prompt Engineer",
    email: "sofia.n@example.com",
    location: "New York, NY",
    remote_preference: "Hybrid",
    years_experience: 3,
    expected_salary: "$130,000",
    industry: "MarTech",
    availability: "Immediate",
    education: "BA Linguistics + MS Data Science, Columbia",
    skills: {
      programming_languages: ["Python", "JavaScript"],
      frameworks: ["LangChain", "Semantic Kernel", "OpenAI SDK"],
      ai_ml: ["NLP", "Sentiment analysis", "Evaluation metrics"],
      llm_experience: ["Prompt optimization", "Few-shot design", "Chain-of-thought", "Guardrails"],
      cloud: ["Azure OpenAI", "AWS Bedrock"],
      devops: ["Basic CI/CD"],
      databases: ["Vector DBs", "PostgreSQL"],
      certifications: ["DeepLearning.AI Prompt Engineering"],
      soft_skills: ["Creative writing", "User empathy", "A/B testing"],
      open_source: ["prompt-templates-hub"],
      projects: ["Marketing copy generation pipeline", "Customer support bot optimization"],
    },
    analysis: {
      ai_match_score: 88,
      skill_match: 91,
      resume_summary:
        "Specialized prompt engineer bridging linguistics and data science. Expert at optimizing LLM outputs for business applications.",
      strengths: [
        "Prompt engineering mastery",
        "Evaluation frameworks",
        "Cross-domain communication",
        "Fast learner",
      ],
      weaknesses: ["Limited systems engineering", "Junior overall experience"],
      recommended_role: "Senior Prompt Engineer / AI Product Specialist",
      leadership_score: 70,
      technical_score: 82,
      communication_score: 95,
      learning_potential: 97,
      career_growth_prediction:
        "Fastest learner in pool — likely to become AI Product Lead within 18 months.",
      rank: "strong",
    },
    pipeline_stage: "interview",
    sources: [
      { type: "portfolio", url: "https://sofiaprompts.dev", label: "Portfolio" },
      { type: "resume", label: "Uploaded Resume" },
    ],
    portfolio_url: "https://sofiaprompts.dev",
  },
  {
    name: "David Kim",
    title: "GenAI Engineer",
    email: "david.kim@example.com",
    location: "Los Angeles, CA",
    remote_preference: "Remote",
    years_experience: 4,
    expected_salary: "$160,000",
    industry: "Media & Entertainment",
    availability: "2 weeks",
    education: "MS AI, UCLA",
    skills: {
      programming_languages: ["Python", "TypeScript", "Swift"],
      frameworks: ["PyTorch", "Stable Diffusion", "LangChain", "React"],
      ai_ml: ["Generative AI", "Diffusion models", "Video AI", "TTS"],
      llm_experience: ["Multimodal LLMs", "Content generation pipelines"],
      cloud: ["GCP", "RunPod"],
      devops: ["Docker", "Modal"],
      databases: ["Pinecone", "S3"],
      certifications: [],
      soft_skills: ["Creative direction", "Product thinking"],
      open_source: ["genai-media-tools (1.5k stars)"],
      projects: ["AI video editing platform", "Personalized content recommender"],
    },
    analysis: {
      ai_match_score: 90,
      skill_match: 87,
      resume_summary:
        "Full-stack GenAI engineer combining creative media expertise with production ML pipeline experience.",
      strengths: [
        "Multimodal AI",
        "Full-stack capability",
        "Creative applications",
        "Strong portfolio",
      ],
      weaknesses: ["Less enterprise experience", "Infrastructure depth"],
      recommended_role: "GenAI Engineer / AI Product Engineer",
      leadership_score: 72,
      technical_score: 88,
      communication_score: 86,
      learning_potential: 92,
      career_growth_prediction: "Well-positioned for AI Product Lead in creative tech.",
      rank: "excellent",
    },
    pipeline_stage: "screening",
    sources: [
      { type: "github", url: "https://github.com/davidkim", label: "GitHub" },
      { type: "portfolio", url: "https://davidgenai.com", label: "Portfolio" },
    ],
    github_url: "https://github.com/davidkim",
    portfolio_url: "https://davidgenai.com",
  },
  {
    name: "Amara Osei",
    title: "Full Stack Developer",
    email: "amara.o@example.com",
    location: "Chicago, IL",
    remote_preference: "Remote",
    years_experience: 4,
    expected_salary: "$120,000",
    industry: "EdTech",
    availability: "Immediate",
    education: "BS Software Engineering, UIUC",
    skills: {
      programming_languages: ["JavaScript", "Python", "Java"],
      frameworks: ["React", "Express", "Spring Boot"],
      ai_ml: ["Basic ML"],
      llm_experience: ["ChatGPT API integration"],
      cloud: ["AWS", "Heroku"],
      devops: ["Docker", "Jenkins"],
      databases: ["MySQL", "MongoDB"],
      certifications: [],
      soft_skills: ["Adaptability", "Team player"],
      open_source: [],
      projects: ["Learning management system", "Student analytics dashboard"],
    },
    analysis: {
      ai_match_score: 72,
      skill_match: 70,
      resume_summary:
        "Competent full-stack developer with EdTech experience. Generalist profile with emerging AI interest.",
      strengths: ["Versatile stack", "EdTech domain knowledge", "Immediate availability"],
      weaknesses: ["Limited AI depth", "No senior-level projects", "Minimal open source"],
      recommended_role: "Mid-level Full Stack Developer",
      leadership_score: 55,
      technical_score: 74,
      communication_score: 82,
      learning_potential: 80,
      career_growth_prediction: "Steady growth with focused AI upskilling.",
      rank: "good",
    },
    pipeline_stage: "sourced",
    sources: [{ type: "resume", label: "Uploaded Resume" }],
  },
  {
    name: "Ryan Mitchell",
    title: "DevOps Engineer",
    email: "ryan.m@example.com",
    location: "Denver, CO",
    remote_preference: "Remote",
    years_experience: 9,
    expected_salary: "$155,000",
    industry: "Cloud Infrastructure",
    availability: "1 month",
    education: "BS Information Systems, Colorado State",
    skills: {
      programming_languages: ["Python", "Bash", "Go"],
      frameworks: ["Terraform", "Ansible", "Pulumi"],
      ai_ml: ["MLOps tooling"],
      llm_experience: ["LLM deployment infrastructure"],
      cloud: ["AWS", "GCP", "Azure"],
      devops: ["Kubernetes", "ArgoCD", "Prometheus", "Grafana"],
      databases: ["PostgreSQL", "InfluxDB"],
      certifications: ["CKA", "AWS DevOps Pro", "Terraform Associate"],
      soft_skills: ["Incident management", "Documentation", "SRE culture"],
      open_source: ["k8s-observability-stack (680 stars)"],
      projects: ["Multi-region K8s platform", "GitOps migration"],
    },
    analysis: {
      ai_match_score: 78,
      skill_match: 75,
      resume_summary:
        "Veteran DevOps/SRE engineer with extensive cloud and Kubernetes expertise. Most experienced candidate in infrastructure.",
      strengths: [
        "Infrastructure mastery",
        "Certifications",
        "SRE best practices",
        "Most experienced",
      ],
      weaknesses: ["Not a software engineer", "Limited application development"],
      recommended_role: "Senior DevOps / Platform Engineer",
      leadership_score: 85,
      technical_score: 86,
      communication_score: 78,
      learning_potential: 70,
      career_growth_prediction:
        "Future leader track — Platform Engineering Manager or Director of SRE.",
      rank: "strong",
    },
    pipeline_stage: "screening",
    sources: [
      { type: "github", url: "https://github.com/ryanmitchell", label: "GitHub" },
      { type: "stackoverflow", label: "Top 2% DevOps tag" },
    ],
    github_url: "https://github.com/ryanmitchell",
  },
  {
    name: "Lisa Zhang",
    title: "Junior React Developer",
    email: "lisa.z@example.com",
    location: "Portland, OR",
    remote_preference: "Hybrid",
    years_experience: 1,
    expected_salary: "$85,000",
    industry: "Startup",
    availability: "Immediate",
    education: "Coding Bootcamp + BS Psychology, Oregon State",
    skills: {
      programming_languages: ["JavaScript", "HTML/CSS"],
      frameworks: ["React", "Tailwind CSS"],
      ai_ml: [],
      llm_experience: ["Used Awgataot for development"],
      cloud: ["Vercel"],
      devops: [],
      databases: ["Firebase"],
      certifications: ["freeCodeCamp Responsive Web Design"],
      soft_skills: ["Eager learner", "UX sensitivity"],
      open_source: [],
      projects: ["Personal portfolio", "Todo app with React"],
    },
    analysis: {
      ai_match_score: 45,
      skill_match: 42,
      resume_summary:
        "Entry-level React developer with bootcamp background. Shows potential but lacks production experience for senior roles.",
      strengths: ["UX awareness", "Motivation", "Modern CSS skills"],
      weaknesses: [
        "Very junior",
        "No production experience",
        "No backend skills",
        "No AI experience",
      ],
      recommended_role: "Junior Frontend Developer (with mentorship)",
      leadership_score: 30,
      technical_score: 48,
      communication_score: 75,
      learning_potential: 88,
      career_growth_prediction: "Needs 2+ years mentorship before senior consideration.",
      rank: "not_recommended",
    },
    pipeline_stage: "rejected",
    sources: [{ type: "resume", label: "Uploaded Resume" }],
  },
  {
    name: "Alex Petrov",
    title: "Staff Software Engineer",
    email: "alex.p@example.com",
    location: "Remote (EU)",
    remote_preference: "Remote",
    years_experience: 12,
    expected_salary: "$210,000",
    industry: "Enterprise SaaS",
    availability: "Negotiable",
    education: "MS Distributed Systems, ETH Zurich",
    skills: {
      programming_languages: ["Go", "Rust", "Python", "TypeScript"],
      frameworks: ["gRPC", "React", "Kafka"],
      ai_ml: ["ML platform engineering"],
      llm_experience: ["Internal LLM tooling", "AI feature flags"],
      cloud: ["AWS", "GCP"],
      devops: ["Kubernetes", "Terraform", "Custom operators"],
      databases: ["CockroachDB", "PostgreSQL", "Redis Cluster"],
      certifications: ["CKA", "AWS SA Pro"],
      soft_skills: ["Architecture", "Mentoring", "Technical strategy"],
      open_source: ["distributed-cache-go (3.2k stars)", "grpc-middleware"],
      projects: ["Global multi-tenant platform", "Zero-downtime migration system"],
    },
    analysis: {
      ai_match_score: 89,
      skill_match: 85,
      resume_summary:
        "Staff-level engineer with deep distributed systems expertise. Highest AI score among senior generalists with leadership potential.",
      strengths: [
        "System design",
        "Scale experience",
        "Technical leadership",
        "Highest experience",
      ],
      weaknesses: ["Not AI-specialist", "EU timezone", "Premium compensation"],
      recommended_role: "Staff Engineer / Engineering Manager",
      leadership_score: 92,
      technical_score: 93,
      communication_score: 87,
      learning_potential: 78,
      career_growth_prediction: "Future leader — VP Engineering or Distinguished Engineer path.",
      rank: "excellent",
    },
    pipeline_stage: "interview",
    sources: [
      { type: "github", url: "https://github.com/alexpetrov", label: "GitHub" },
      { type: "publication", label: "Conference speaker (QCon, KubeCon)" },
    ],
    github_url: "https://github.com/alexpetrov",
  },
];
